export const SELECT_RESERVATION = 'SELECT_RESERVATION';
/** Авторизации и регистрация */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const SET_FIELD_ERROR = "SET_FIELD_ERROR"
export const CLEAR_FIELD_ERROR = "CLEAR_FIELD_ERROR"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS"
export const GET_INFO_ERROR = "GET_INFO_ERROR"
export const CHANGE_USER_AVATAR_SUCCESS = "CHANGE_USER_AVATAR_SUCCESS"
export const CHANGE_USER_AVATAR_ERROR = "CHANGE_USER_AVATAR_ERROR"
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS"
export const CHANGE_USER_PASSWORD_ERROR = "CHANGE_USER_PASSWORD_ERROR"
export const SAVE_RECOVERY_TOKEN = "SAVE_RECOVERY_TOKEN"
export const DELETE_RECOVERY_TOKEN = "DELETE_RECOVERY_TOKEN"
export const CHANGE_HOTEL_AMENITY = "CHANGE_HOTEL_AMENITY"
export const SET_USER_TYPE = "SET_USER_TYPE"
export const CHECK_FIRST_BOOKING = "CHECK_FIRST_BOOKING"

/** Создание и просмотр отеля у партнера */
export const HOTEL_CREATE_SUCCESS = "HOTEL_CREATE_SUCCESS"
export const HOTEL_CREATE_ERROR = "HOTEL_CREATE_ERROR"
export const CLEAR_FIELD_HOTEL_ERROR = "CLEAR_FIELD_HOTEL_ERROR"
export const HOTEL_TRAVELLINE_ERROR = "HOTEL_TRAVELLINE_ERROR"
export const CLEAR_HOTEL_ALL_ERROR = "CLEAR_HOTEL_ALL_ERROR"
export const GET_OBJECTS_SUCCESS = "GET_OBJECTS_SUCCESS"
export const GET_OBJECTS_FOR_DOCUMENTS_SECCESS = "GET_OBJECTS_FOR_DOCUMENTS_SECCESS"
export const GET_OBJECTS_ERROR = "GET_OBJECTS_ERROR"
export const GET_ROOMS_LIST_PARTNER_SUCCESS = "GET_ROOMS_LIST_PARTNER_SUCCESS"
export const GET_ROOMS_LIST_PARTNER_ERROR = "GET_ROOMS_LIST_PARTNER_ERROR"
export const HOTEL_ROOM_CREATE_SUCCESS = "HOTEL_ROOM_CREATE_SUCCESS"
export const HOTEL_ROOM_CREATE_ERROR = "HOTEL_ROOM_CREATE_ERROR"
export const EDIT_HOTEL_ROOM_SUCCESS = "EDIT_HOTEL_ROOM_SUCCESS"
export const EDIT_HOTEL_ROOM_ERROR = "EDIT_HOTEL_ROOM_ERROR"
export const CREATE_TARIFF_SUCCESS = "CREATE_TARIFF_SUCCESS"
export const CREATE_TARIFF_ERROR = "CREATE_TARIFF_ERROR"
export const CREATE_BED_SUCCESS = "CREATE_BED_SUCCESS"
export const CREATE_BED_ERROR = "CREATE_BED_ERROR"
export const GET_BED_TYPES = "GET_BED_TYPES"
export const GET_SERVICE_ROOM_SUCCESS = "GET_SERVICE_ROOM_SUCCESS"
export const GET_SERVICE_ROOM_ERROR = "GET_SERVICE_ROOM_ERROR"
export const GET_ROOM_INFO_SUCCESS = "GET_ROOM_INFO_SUCCESS"
export const CLEAR_ROOM_INFO = "CLEAR_ROOM_INFO"
export const GET_ROOM_INFO_ERROR = "GET_ROOM_INFO_ERROR"
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
export const DELETE_ROOM_ERROR = "DELETE_ROOM_ERROR"
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS"
export const DELETE_HOTEL_ERROR = "DELETE_HOTEL_ERROR"
export const GET_HOTEL_INFO_SUCCESS = "GET_HOTEL_INFO_SUCCESS"
export const GET_HOTEL_INFO_ERROR = "GET_HOTEL_INFO_ERROR"
export const UPLOAD_HOTEL_IMAGE_SUCCESS = "UPLOAD_HOTEL_IMAGE_SUCCESS"
export const UPLOAD_HOTEL_IMAGE_ERROR = "UPLOAD_HOTEL_IMAGE_ERROR"
export const DELETE_HOTEL_IMAGE_SUCCESS = "DELETE_HOTEL_IMAGE_SUCCESS"
export const DELETE_ROOM_IMAGE_SUCCESS = "DELETE_ROOM_IMAGE_SUCCESS"
export const UPLOAD_ROOM_IMAGE_SUCCESS = "UPLOAD_ROOM_IMAGE_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const CLEAR_SERVICES = "CLEAR_SERVICES"
export const DELETE_TARIFF_SUCCESS = "DELETE_TARIFF_SUCCESS"
export const DELETE_BED_SUCCESS = "DELETE_BED_SUCCESS"
export const REVOKE_HOTEL_SUCCESS = "REVOKE_HOTEL_SUCCESS"
export const REVOKE_HOTEL_ERROR = "REVOKE_HOTEL_ERROR"
export const GET_LIST_TARIFF_SUCCESS = "GET_LIST_TARIFF_SUCCESS"
export const EDIT_ROOM_TARIFF_SUCCESS = 'EDIT_ROOM_TARIFF_SUCCESS'
export const DELETE_HOTEL_ERROR_IMAGE = "DELETE_HOTEL_ERROR_IMAGE"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SAVE_MAIN_IMAGE_SUCCESS = "SAVE_MAIN_IMAGE_SUCCESS"
export const GET_TYPE_HOTELS = "GET_TYPE_HOTELS"
export const CLEAR_HOTEL_INFO ="CLEAR_HOTEL_INFO"
export const SET_PAYMENT_TYPE_SUCCESS = "SET_PAYMENT_TYPE_SUCCESS"
export const CLEAR_HOTEL_IMAGE = "CLEAR_HOTEL_IMAGE"
export const GET_MEAL_TYPE = "GET_MEAL_TYPE"

/** Каталог */
export const GET_MAP_HOTELS = "GET_MAP_HOTELS"
export const GET_HOTELS_REQUEST = "GET_HOTELS_REQUEST"
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS"
export const CLEAR_HOTELS = "CLEAR_HOTELS"
export const SET_CITY = "SET_CITY"
export const CLEAR_CITY = "CLEAR_CITY"
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS"
export const GET_HOTEL_ERROR = "GET_HOTEL_ERROR"
export const CLEAR_HOTEL_ERROR = "CLEAR_HOTEL_ERROR"
export const SAVE_TARRIFF = "SAVE_TARRIFF"
export const SET_POPULAR = "SET_POPULAR"
export const GET_SIMILAR_REQUEST = "GET_SIMILAR_REQUEST"
export const GET_SIMILAR_SUCCESS = "GET_SIMILAR_SUCCESS"
export const CLEAR_HOTEL = "CLEAR_HOTEL"
export const CLEAR_SIMILAR_HOTELS = "CLEAR_SIMILAR_HOTELS"
export const SET_COORDINATES = "SET_COORDINATES"
export const CLEAR_COORDINATES = "CLEAR_COORDINATES"
export const GET_COMMENTS_MODAL = "GET_COMMENTS_MODAL"
export const GET_COMMENTS_ROOM = "GET_COMMENTS_ROOM"
export const GET_CATALOG_FILTERS = "GET_CATALOG_FILTERS"
export const GET_SIGHTS_FILTERS = "GET_SIGHTS_FILTERS"
export const GET_SUBWAY_FILTERS = "GET_SUBWAY_FILTERS"
export const CLEAR_SUBWAY_FILTERS = "CLEAR_SUBWAY_FILTERS"
export const GET_POPULAR_FILTERS = "GET_POPULAR_FILTERS"



/** Типы событий для бронирования */
export const GET_HOTEL_FOR_BOOK_SUCCESS = "GET_HOTEL_FOR_BOOK_SUCCESS"
export const GET_HOTEL_FOR_BOOK_ERROR = "GET_HOTEL_FOR_BOOK_ERROR"
export const GET_ROOM_FOR_BOOK_SUCCESS = "GET_ROOM_FOR_BOOK_SUCCESS"
export const GET_ROOM_FOR_BOOK_ERROR = "GET_ROOM_FOR_BOOK_ERROR"


/** Типы событий для бронирования */
export const GET_BOOKINGS_CLIENT_SUCCESS = "GET_BOOKINGS_CLIENT_SUCCESS"
export const GET_BOOKINGS_CLIENT_ERROR = "GET_BOOKINGS_CLIENT_ERROR"
export const CANCEL_CLIENT_BOOK_SUCCESS = "CANCEL_CLIENT_BOOK_SUCCESS"
export const CANCEL_CLIENT_BOOK_ERROR = "CANCEL_CLIENT_BOOK_ERROR"
export const CANCEL_BOOKING_PARTNER_SUCCESS = "CANCEL_BOOKING_PARTNER_SUCCESS"
export const CANCEL_BOOKING_PARTNER_ERROR = "CANCEL_BOOKING_PARTNER_ERROR"
export const GET_CURRENT_BOOK_CLIENT_SUCCESS = "GET_CURRENT_BOOK_CLIENT_SUCCESS"
export const GET_CURRENT_BOOK_CLIENT_ERROR = "GET_CURRENT_BOOK_CLIENT_ERROR"
export const GET_HOTEL_STATS_SUCCESS = "GET_HOTEL_STATS_SUCCESS"
export const CONFIRM_BOOK_SUCCESS = "CONFIRM_BOOK_SUCCESS"
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS"
export const LOCK_SUCCESS = 'LOCK_SUCCESS'
export const LOCK_ERROR = 'LOCK_ERROR'
export const CREATE_BOOK_ERROR = "CREATE_BOOK_ERROR"
export const GET_REASON_FOR_CANCEL_SUCCESS = "GET_REASON_FOR_CANCEL_SUCCESS"
export const GET_SUB_REASON_FOR_CANCEL_SUCCESS = "GET_SUB_REASON_FOR_CANCEL_SUCCESS"
export const GET_CLIENT_CALC_PENALTY = "GET_CLIENT_CALC_PENALTY"
export const CLEAR_ERROR_BOOKING = "CLEAR_ERROR_BOOKING"
export const CLEAR_BOOK_FORM_ERROR = "CLEAR_BOOK_FORM_ERROR"
export const GET_PARTNER_BOOKING_REJECT_REASONS = "GET_BOOKING_PARTNER_REJECT_REASONS"
export const GET_PARTNER_BOOKING_REJECT_REASONS_ERROR = "GET_BOOKING_PARTNER_REJECT_REASONS_ERROR"
export const GET_COUNT_ACTIVE_BOOKING = "GET_COUNT_ACTIVE_BOOKING"
export const CLEAR_BOOK_FORM_ERROR_FIELD = "CLEAR_BOOK_FORM_ERROR_FIELD"


/** Типы событий для получения инфы общей информации */
export const GET_GENERAL_INFO_SUCCESS = "GET_GENERAL_INFO_SUCCESS"
export const GET_SOCIAL_MEDIAS_SUCCESS = "GET_SOCIAL_MEDIAS_SUCCESS"
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const GET_FOOTER_LINKS = "GET_FOOTER_LINKS"
export const GET_PAYMENTS = "GET_PAYMENTS"
export const GET_TERMS_RESEARCH = "GET_TERMS_RESEARCH"

/** Избраное */
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS"

/**FAQ*/
export const GET_LIST_FAQ_SUCCESS = "GET_LIST_FAQ_SUCCESS"
export const GET_GROUP_FAQ_SUCCESS = "GET_GROUP_FAQ_SUCCESS"

/** Коментарии */
export const GET_REVIEWS_CLIENT_SUCCESS = "GET_REVIEWS_CLIENT_SUCCESS"
export const CREATE_REVIEW_CLIENT_SUCCESS = "CREATE_REVIEW_CLIENT_SUCCESS"
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const ANSWER_PARTNER_SUCCESS = "ANSWER_PARTNER_SUCCESS"
export const CLEAR_STATE = "CLEAR_STATE"

/** Уведомления */
export const GET_NOTIFICATION_PARTNER_SUCCESS = "GET_NOTIFICATION_PARTNER_SUCCESS"
export const DELETE_UNREAD_NOTIFICATION = "DELETE_UNREAD_NOTIFICATION"
export const COUNT_NOTIFICATIONS_SUCCESS = "COUNT_NOTIFICATIONS_SUCCESS"

/** Цены */
export const GET_LIST_PRICES_SUCCESS = "GET_LIST_PRICES_SUCCESS"
export const CLEAR_LIST_PRICES = "CLEAR_LIST_PRICES"
/** Последний просмотр отеля */
export const SET_LAST_HOTELS = "SET_LAST_HOTELS"

/** Модерация партнера */
export const GET_LIST_MODERATION_SUCCESS = "GET_LIST_MODERATION_SUCCESS"
export const GET_CURRENT_MODERATION = "GET_CURRENT_MODERATION"
export const CREATE_ANSWER_MODERATION = "CREATE_ANSWER_MODERATION"

export const GET_TITLES = "GET_TITLES"
export const GET_TITLE = "GET_TITLE"
export const GET_TEGS = "GET_TEGS"

export const GET_DIRECTIONS = "GET_DIRECTIONS"
export const GET_DIRECTIONS_INFO = "GET_DIRECTIONS_INFO"
export const GET_PARTNERS = "GET_PARTNERS"
export const GET_PARTNERS_PAGE_INFO = "GET_PARTNERS_PAGE_INFO"
export const GET_DIRECTIONS_PAGE_TITLE = "GET_DIRECTIONS_PAGE_TITLE"

export const GET_IMAGES_MAIN = "GET_IMAGES_MAIN"

export const SUBSCRIBE_ERROR_CLEAR = "SUBSCRIBE_ERROR_CLEAR"
export const SUBSCRIBE_FALIED = "SUBSCRIBE_FALIED"
export const SUBSCRIBE_SECCESS = "SUBSCRIBE_SECCESS"


export const CHECK_EMAIL_SECCESS = "CHECK_EMAIL_SECCESS"

export const CALL_ERROR = "CALL_ERROR"
export const CLEAR_CALL_ERROR = "CLEAR_CALL_ERROR"
export const CLEAR_FIELD_CALL_ERROR = "CLEAR_FIELD_CALL_ERROR"


export const SHOW_AUTH_MODAL = "SHOW_AUTH_MODAL"

/** Таблица цен */
export const GET_CALENDAR_PRICES_SUCCESS = "GET_CALENDAR_PRICES_SUCCESS"
export const ERROR_CALENDAR = "ERROR_CALENDAR"
export const CLEAR_ERROR_CALENDAR = "CLEAR_ERROR_CALENDAR"
export const SAVE_ERROR_INTEGRATION = "SAVE_ERROR_INTEGRATION"

/** Отчеты */
export const GET_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS"
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS"
export const CLEAR_REPORTS = "CLEAR_REPORTS"

/** Реквизиты */
export const GET_REQUISITES_SECCESS = "GET_REQUISITES_SECCESS"
export const GET_REQUISITES_ERROR = "GET_REQUISITES_ERROR"

/** Приложение */
export const GET_APP_DOWNLOAD_URL = "GET_APP_DOWNLOAD_URL"


/** Архивные отели */
export const ARCHIVE_HOTEL_SUCCESS = "ARCHIVE_HOTEL_SUCCESS"
export const GET_ARCHIVE_HOTELS = "GET_ARCHIVE_HOTELS"
export const RESTORE_ARCHIVE_HOTEL = "RESTORE_ARCHIVE_HOTEL"
export const GET_COUNT_ARCHIVE_BOOKING = "GET_COUNT_ARCHIVE_BOOKING"


export const START_REQUEST = "START_REQUEST"
export const STOP_REQUEST = "STOP_REQUEST"