export const INTEGRATION_TYPE_NONE = 0
export const INTEGRATION_TYPE_BNOVO = 1
export const INTEGRATION_TYPE_TRAVELLINE_FIRST = 2
export const INTEGRATION_TYPE_HOTELBOOK = 3
export const INTEGRATION_TYPE_TRAVELLINE_SECOND = 4
