---

.build:
  stage: build
  image: node:16-alpine3.15
  environment:
    name: $DEPLOYMENT_ENV
  artifacts:
    paths:
      - project.tar.gz
  cache:
    key: ${CI_JOB_STAGE}__${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  script:
    - cat ${ARTEFACT_EXCLUDE_DIRS} > ../exclude.txt
    - echo "Insert .env file from CI variables (DEPLOY ENVIRONMENT $DEPLOYMENT_ENV)"
    - rm -f .env && rm -f .env.*
    - cat $DOCKER_BUILD_ENV > .env
    - npm set cache .npm
    - npm install --prefer-offline -g serve node-sass
    - npm install --prefer-offline --legacy-peer-deps
    - CI=false npm run build
    - tar -X ../exclude.txt -czf ../project.tar.gz .
    - mv ../project.tar.gz ./project.tar.gz
