export const configDocumentsField = [
    "doc_shipment_description",
    "shipping_organization",
    "shipping_country",
    "shipping_zip",
    "shipping_region",
    "shipping_city",
    "shipping_street",
    "shipping_house",
    "shipping_office",
    "shipping_second_name",
    "shipping_first_name",
    "shipping_mid_name",
    "shipping_phone",
]